title:              Field
email:              bexultan.rakhim AT gmail.com
description:        blog about science
author:             Bex
baseurl:            "/field"
url:                "https://bexultanrakhim.github.io"

# Social Profiles
twitter_username:   
github_username:    bexultanrakhim
facebook_username:  
instagram_username:  
linkedin_username:



# Build settings
markdown:           kramdown
paginate:           4
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
